### ISSUE TITLE
Invalid readme

### ISSUE THREAD

**Issue by streefje1996** [infosupport/azureml-cookiecutter#7]
- [ ] Unable to set up conda environment using the code from the readme `conda env create -f conda_dependencies.yml` 
- [ ] The parameters/flags for the tasks scripts are invalid
- [ ] In working with data "Fro that reason, the project contains"
- [ ] In working with data "script to upload the datasets to the 
azure workspace after you've created"

**Comment by wmeints** [comment]
Hey Stefan, Thanks for reporting this. We're planning on changing the template to regular-old python. That should fix the issues with the scripts.
